# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flakewatcher/ui_xml/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(775, 644)
		self.FlakeOutput = QtWidgets.QLabel(MainWindow)
		self.FlakeOutput.setGeometry(QtCore.QRect(10, 60, 751, 571))
		font = QtGui.QFont()
		font.setFamily("Noto Mono")
		self.FlakeOutput.setFont(font)
		self.FlakeOutput.setStyleSheet("background-color: #1E1E1E; color: #D3D7CF;")
		self.FlakeOutput.setText("")
		self.FlakeOutput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
		self.FlakeOutput.setObjectName("FlakeOutput")
		self.StartButton = QtWidgets.QPushButton(MainWindow)
		self.StartButton.setGeometry(QtCore.QRect(350, 0, 86, 34))
		self.StartButton.setObjectName("StartButton")

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "flakewatcher"))
		self.StartButton.setText(_translate("MainWindow", "Start"))
